# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [7]:
a = pd.Series(np.random.randint(1,5,100))
b = pd.Series(np.random.randint(1,4,100))
c = pd.Series(np.random.randint(10000,30001,100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [16]:
x = pd.concat([a,b,c],axis =1)
x.head()

   0  1      2
0  2  2  10684
1  2  2  19063
2  2  2  23785
3  3  1  23620
4  2  1  20324

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [17]:
x.columns = ["bedrs","bathrs","price_sqr_meter"]
x.head()

   bedrs  bathrs  price_sqr_meter
0      2       2            10684
1      2       2            19063
2      2       2            23785
3      3       1            23620
4      2       1            20324

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [19]:
bigcolumn = pd.concat([a,b,c])
bigcolumn

0         2
1         2
2         2
3         3
4         2
      ...
95    12728
96    25691
97    27202
98    13494
99    22372
Length: 300, dtype: int64

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [21]:
True

True

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [22]:
bigcolumn.reset_index()

     index      0
0        0      2
1        1      2
2        2      2
3        3      3
4        4      2
..     ...    ...
295     95  12728
296     96  25691
297     97  27202
298     98  13494
299     99  22372

[300 rows x 2 columns]