# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [31]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [32]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')
drinks = drinks.drop("country",axis=1)
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,0,0,0,0.0,AS
1,89,132,54,4.9,EU
2,25,0,14,0.7,AF
3,245,138,312,12.4,EU
4,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [33]:
drinks.groupby(by="continent").mean()["total_litres_of_pure_alcohol"].index[0]

'AF'

### Step 5. For each continent print the statistics for wine consumption.

In [34]:
drinks.groupby("continent").agg(['sum','mean','std','var','count','max','min'])["wine_servings"]

            sum        mean        std          var  count  max  min
continent
AF          862   16.264151  38.846419  1509.044267     53  233    0
AS          399    9.068182  21.667034   469.460359     44  123    0
EU         6400  142.222222  97.421738  9490.994949     45  370    0
OC          570   35.625000  64.555790  4167.450000     16  212    0
SA          749   62.416667  88.620189  7853.537879     12  221    1

### Step 6. Print the mean alcohol consumption per continent for every column

In [35]:
drinks.groupby(by="continent").mean()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcohol consumption per continent for every column

In [36]:
drinks.groupby(by="continent").median()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [37]:
drinks.groupby("continent").agg(['mean','max','min'])

          beer_servings          spirit_servings          wine_servings       \
                   mean  max min            mean  max min          mean  max
continent
AF            61.471698  376   0       16.339623  152   0     16.264151  233
AS            37.045455  247   0       60.840909  326   0      9.068182  123
EU           193.777778  361   0      132.555556  373   0    142.222222  370
OC            89.687500  306   0       58.437500  254   0     35.625000  212
SA           175.083333  333  93      114.750000  302  25     62.416667  221

              total_litres_of_pure_alcohol
          min                         mean   max  min
continent
AF          0                     3.007547   9.1  0.0
AS          0                     2.170455  11.5  0.0
EU          0                     8.617778  14.4  0.0
OC          0                     3.381250  10.4  0.0
SA          1                     6.308333   8.3  3.8